# Generated by Django 5.1.2 on 2025-02-07 06:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Plan",
            fields=[
                ("plan_id", models.AutoField(primary_key=True, serialize=False)),
                ("plan_name", models.TextField()),
                ("price", models.FloatField()),
                ("max_queries", models.IntegerField(blank=True, null=True)),
                ("max_quizzes", models.IntegerField(blank=True, null=True)),
            ],
            options={
                "db_table": "plans",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="UserStats",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("total_quizzes", models.IntegerField(blank=True, null=True)),
                ("last_activity", models.DateTimeField(blank=True, null=True)),
                ("average_score", models.FloatField(blank=True, null=True)),
                ("subject_averages", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "db_table": "user_stats",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Voucher",
            fields=[
                ("voucher_id", models.AutoField(primary_key=True, serialize=False)),
                ("transaction_id", models.TextField(unique=True)),
                ("card_id", models.IntegerField()),
                ("amount", models.FloatField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("used", models.BooleanField(default=False)),
            ],
            options={
                "db_table": "vouchers",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                ("payment_id", models.AutoField(primary_key=True, serialize=False)),
                ("transaction_id", models.TextField()),
                ("amount", models.FloatField()),
                ("payment_date", models.DateTimeField(blank=True, null=True)),
                ("receiver_id_card", models.CharField(max_length=255)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "payments",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Quizzes",
            fields=[
                ("quiz_id", models.AutoField(primary_key=True, serialize=False)),
                ("topic", models.TextField()),
                ("matter", models.TextField()),
                ("questions_count", models.IntegerField()),
                ("score", models.FloatField()),
                ("created_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "quizzes",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("remaining_queries", models.IntegerField(default=0)),
                ("remaining_quizzes", models.IntegerField(default=0)),
                (
                    "plan",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="medicaltutordjapp.plan",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "stats",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to="medicaltutordjapp.userstats",
                    ),
                ),
            ],
        ),
    ]
