# Generated by Django 5.1.2 on 2025-01-18 19:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Plans",
            fields=[
                ("plan_id", models.AutoField(primary_key=True, serialize=False)),
                ("plan_name", models.TextField()),
                ("price", models.FloatField()),
                ("max_queries_per_month", models.IntegerField(blank=True, null=True)),
                ("max_quizzes_per_month", models.IntegerField(blank=True, null=True)),
            ],
            options={
                "db_table": "plans",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="UserStats",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("total_quizzes", models.IntegerField(blank=True, null=True)),
                ("last_activity", models.DateTimeField(blank=True, null=True)),
                ("average_score", models.FloatField(blank=True, null=True)),
            ],
            options={
                "db_table": "user_stats",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Payments",
            fields=[
                ("payment_id", models.AutoField(primary_key=True, serialize=False)),
                ("amount", models.FloatField()),
                ("card_number", models.TextField()),
                ("payment_date", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "payments",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Quizzes",
            fields=[
                ("quiz_id", models.AutoField(primary_key=True, serialize=False)),
                ("topic", models.TextField()),
                ("matter", models.TextField()),
                ("questions_count", models.IntegerField()),
                ("score", models.FloatField()),
                ("created_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "quizzes",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="medicaltutordjapp.plans",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
