# Generated by Django 5.1.2 on 2025-03-23 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("medicaltutordjapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="plan",
            name="plan_name",
            field=models.TextField(max_length=255),
        ),
    ]
