# Generated by Django 5.1.2 on 2025-01-20 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("medicaltutordjapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userstats",
            name="subject_averages",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
