# Generated by Django 5.1.2 on 2025-01-19 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("medicaltutordjapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="plan",
            options={"managed": False},
        ),
        migrations.AlterModelOptions(
            name="quizzes",
            options={"managed": True},
        ),
        migrations.AlterModelOptions(
            name="userstats",
            options={"managed": True},
        ),
        migrations.AddField(
            model_name="payment",
            name="receiver_id_card",
            field=models.CharField(default="1234567890", editable=False, max_length=20),
        ),
    ]
