# Generated by Django 5.1.2 on 2025-05-11 23:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicaltutordjapp', '0002_processedsubmission'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='processedsubmission',
            name='submission_id',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='processedsubmission',
            unique_together={('submission_id', 'user')},
        ),
        migrations.AddIndex(
            model_name='processedsubmission',
            index=models.Index(fields=['submission_id', 'user'], name='medicaltuto_submiss_612b2d_idx'),
        ),
    ]
