# Generated by Django 5.1.2 on 2025-03-01 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("medicaltutordjapp", "0002_userprofile_last_chat_content_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="voucher",
            name="card_id",
            field=models.CharField(max_length=255),
        ),
    ]
