# Generated by Django 5.1.2 on 2025-03-23 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("medicaltutordjapp", "0002_alter_plan_plan_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="plan",
            name="plan_name",
            field=models.CharField(max_length=255),
        ),
    ]
