# Generated by Django 5.1.2 on 2025-04-01 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("medicaltutordjapp", "0003_alter_plan_plan_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="transaction_id",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="voucher",
            name="transaction_id",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
