# Generated by Django 5.1.2 on 2025-05-13 03:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicaltutordjapp', '0004_processedsubmission_processed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizzes',
            name='submission',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quiz', to='medicaltutordjapp.processedsubmission'),
        ),
    ]
