# Generated by Django 5.1.2 on 2025-05-13 04:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicaltutordjapp', '0005_quizzes_submission'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizzes',
            name='submission',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='quiz', to='medicaltutordjapp.processedsubmission'),
        ),
        migrations.AddConstraint(
            model_name='quizzes',
            constraint=models.UniqueConstraint(fields=('submission',), name='unique_quiz_per_submission'),
        ),
    ]
